// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO6p4dX4vAYKaJkDFoBOTO4uUxYedRe8E',
    appId: '1:433417656894:web:01a546b4b4610a60160f6f',
    messagingSenderId: '433417656894',
    projectId: 'anti-theft-detection-2d6d8',
    authDomain: 'anti-theft-detection-2d6d8.firebaseapp.com',
    storageBucket: 'anti-theft-detection-2d6d8.appspot.com',
    measurementId: 'G-N94TVCTMWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-TibXxJtfMt5C75N1La5wgirtIH--LA',
    appId: '1:433417656894:android:b121dd5aa565cda8160f6f',
    messagingSenderId: '433417656894',
    projectId: 'anti-theft-detection-2d6d8',
    storageBucket: 'anti-theft-detection-2d6d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5tZri7hQ1-6oa-nQckDEJuurOQDdntQ',
    appId: '1:433417656894:ios:ab2c6adeb8b440ce160f6f',
    messagingSenderId: '433417656894',
    projectId: 'anti-theft-detection-2d6d8',
    storageBucket: 'anti-theft-detection-2d6d8.appspot.com',
    iosBundleId: 'com.example.antiTheft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt5tZri7hQ1-6oa-nQckDEJuurOQDdntQ',
    appId: '1:433417656894:ios:0b3acdd60adb3258160f6f',
    messagingSenderId: '433417656894',
    projectId: 'anti-theft-detection-2d6d8',
    storageBucket: 'anti-theft-detection-2d6d8.appspot.com',
    iosBundleId: 'com.example.antiTheft.RunnerTests',
  );
}
